### ISSUE TITLE
[Suggestion] Check if TAP driver is already installed

### ISSUE THREAD

**Issue by Darthagnon** [DoM1niC/PlayHide#14]
Would it be possible to implement a check to see if the TAP driver needs installing? e.g. I have previously installed OpenVPN which installed the TAP driver. Running PlayHide, it tries to install the TAP driver again. I can, of course, cancel it and PlayHide will work perfectly. Avoids reinstalling stuff that is already installed.

**Comment by DoM1niC** [comment]
In the Server Package I add in drivers a Batch file to add a second TAP Device, the last PlayHide Version identify the Adapter by the given Name like PlayHide VPN, the Server Version could setup the used Adapter name in settings.ini, in my Tests the DHCP Client don't work probably. 

If you be the Server you will stay in the Network with your Clients, a Client on Server side is also not needed.
