### ISSUE TITLE
Server 

### ISSUE THREAD

**Issue by KanterPL** [DoM1niC/PlayHide#16]
Can you make video how to setup server and how to connect to this server? Could you record from your perspective (creating server) and your friend (joining to this server) please? And record how to add 2nd adapter please

**Comment by DoM1niC** [comment]
Is possible but you don't need a 2nd Adapter.... just start the Server and forward the Port 1400 as UDP in your Router. 

The new Client include an entry in the server.ini, just replace the IP with your Domain / IP.

**Comment by KanterPL** [comment]
Okay. Thanks for answering

**Comment by KanterPL** [comment]
Where is this server.ini?

**Comment by DoM1niC** [comment]
@KanterPL  the server.ini is in the Client from PlayHide with a Local example Part, you just replace the IP= to your DynDNS or IP.
