### ISSUE TITLE
Website/Homepage https://playhide.tk/ down?

### ISSUE THREAD

**Issue by Darthagnon** [DoM1niC/PlayHide#19]
The homepage for this project, https://playhide.tk/, is currently (11/06/2020) down. Playhide Server application binaries could only be obtained there, as far as I know.

Best of luck with the project, DoM1nic. Hope all is well!

**Comment by Darthagnon** [comment]
I'm an idiot; I had save the old homepage, https://playhide.tk/, as a shortcut on my computer. The homepage has changed to https://playhide.eu/

**Comment by DoM1niC** [comment]
No Problem :)
