### ISSUE TITLE
[General] PlayHide as Server

### ISSUE THREAD

**Issue by DoM1niC** [DoM1niC/PlayHide#8]
OpenVPN as Server with PlayHide GUI and Config

**Comment by Darthagnon** [comment]
Does this mean e.g. I'll be able to click "Host Server" on my PC in the UK, and my bro in Italy can click "Join server" on his PC, and connect directly to my PC?

**Comment by DoM1niC** [comment]
You start the Server and your Friends configure the server.ini, I edit the Package 7z with the local settings, the Client musst replace the IP to your external IP or DynDNS / Domain, and you need to forward the Port in your Router (1400 as UDP).

**Comment by o0Julia0o** [comment]
What do the clients have to do, to join a Custom-Server?

Server does: ServerMode=1
And after that start PlayHide.

And Clients? Join #GER1 or #GER2?
